"""tabla producto modificada

Revision ID: 08c7a8c53ce0
Revises: deb55cb1f428
Create Date: 2025-08-25 16:40:49.546475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c7a8c53ce0'
down_revision = 'deb55cb1f428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
