"""initial tables

Revision ID: 6b258d8887e4
Revises: 89b686ec9663
Create Date: 2025-09-04 16:26:20.288877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b258d8887e4'
down_revision = '89b686ec9663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalle_ventas_venta_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalle_ventas_producto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['producto_id'], ['id'])
        batch_op.create_foreign_key(None, 'ventas', ['venta_id'], ['id'])

    with op.batch_alter_table('detalles_orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ventas_usuarios_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuarios_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ventas_usuarios_id_fkey'), 'usuarios', ['usuarios_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detalles_orden', schema=None) as batch_op:
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_ventas_producto_id_fkey'), 'producto', ['producto_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('detalle_ventas_venta_id_fkey'), 'ventas', ['venta_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
