"""initial tables

Revision ID: 89b686ec9663
Revises: 00c7dea5e44c
Create Date: 2025-09-03 16:33:23.078257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b686ec9663'
down_revision = '00c7dea5e44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_cliente', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_column('correo_cliente')

    # ### end Alembic commands ###
