"""initial tables

Revision ID: 92bc471692c8
Revises: 21c58c0cf3a3
Create Date: 2025-09-03 14:27:03.155510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bc471692c8'
down_revision = '21c58c0cf3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuarios_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('ventas_cliente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuarios_id'], ['id'])
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ventas_cliente_id_fkey'), 'usuarios', ['cliente_id'], ['id'])
        batch_op.drop_column('usuarios_id')

    # ### end Alembic commands ###
