"""Agrega columna contrasena_hash a usuarios

Revision ID: b4649a7a70d8
Revises: 
Create Date: 2025-07-09 14:20:26.406614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4649a7a70d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=mysql.LONGBLOB(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=mysql.LONGBLOB(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('historial_inventario', schema=None) as batch_op:
        batch_op.alter_column('fecha_movimiento',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('fecha_actualizacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('pedidos_futuros', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=mysql.LONGBLOB(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=mysql.LONGBLOB(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('cliente', 'empleado', 'administrador'),
               nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('contrasena')

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('fecha_venta',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('total',
               existing_type=mysql.LONGBLOB(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
        batch_op.alter_column('fecha_venta',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('cliente', 'empleado', 'administrador'),
               nullable=False)
        batch_op.drop_column('contrasena_hash')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('pedidos_futuros', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.Float(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('historial_inventario', schema=None) as batch_op:
        batch_op.alter_column('fecha_movimiento',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.Float(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.Float(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
