"""Crear o actualizar tablas para notificaciones y estados de ventas

Revision ID: edd706479c6e
Revises: c43399c548ee
Create Date: 2025-09-18 14:00:55.901183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd706479c6e'
down_revision = 'c43399c548ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalle_ventas_producto_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalle_ventas_venta_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ventas', ['venta_id'], ['id'])
        batch_op.create_foreign_key(None, 'producto', ['producto_id'], ['id'])

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ventas_usuarios_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuarios_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ventas_usuarios_id_fkey'), 'usuarios', ['usuarios_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_ventas_venta_id_fkey'), 'ventas', ['venta_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('detalle_ventas_producto_id_fkey'), 'producto', ['producto_id'], ['id'], ondelete='CASCADE')

    op.drop_table('lola')
    # ### end Alembic commands ###
