"""Crear o actualizar tablas para notificaciones y estados de ventas

Revision ID: f39ed685c6ce
Revises: f53b82c14e28
Create Date: 2025-10-01 14:37:40.763342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39ed685c6ce'
down_revision = 'f53b82c14e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=30), nullable=True))
        batch_op.drop_constraint(batch_op.f('ventas_usuarios_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuarios_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ventas_usuarios_id_fkey'), 'usuarios', ['usuarios_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
